FROM ubuntu:18.04
LABEL "maintainer"="vital987<apoorvvyavahare@pm.me>"
ARG DEBIAN_FRONTEND=non-interactive
ENV LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8 \
	LC_ALL=C.UTF-8 \
	TZ="Asia/Kolkata"
SHELL ["/bin/bash", "-c"]
RUN rm -rf /etc/apt/sources.list && \
	bash -c 'echo -e "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse\ndeb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse\ndeb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse\ndeb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse\ndeb http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse\ndeb-src http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse\ndeb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse\ndeb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse\ndeb http://archive.canonical.com/ubuntu focal partner\ndeb-src http://archive.canonical.com/ubuntu focal partner" >/etc/apt/sources.list' && \
	apt-get update && \
	apt-get install --no-install-recommends -y \
	tzdata \
    supervisor && \
    mkdir -p /config/supervisor && \
    echo -e "[supervisord]\nnodaemon=true\n\n[include]\nuser=root\nfiles = /config/supervisor/*.conf" > /config/supervisord.conf && \
	apt-get clean autoclean && \
	apt-get autoremove -y
CMD ["supervisord", "-c", "/config/supervisord.conf"]
